export const DEFAULT_THEME_POOL = [
  'Gravity',
  'Vintage',
  'Dusk',
  'Corroded',
  'Celebration',
  'Mirror',
  'Transport',
  'Order',
  'Tabletop',
  'Isometric',
  'Entropy',
  '90°',
  'Bloom',
  'Portal',
  'Duality',
  'Drift',
  'Neon',
  'Signal',
  'Loop',
  'Glitch',
  'Mutation',
  'Rift',
  'Silence',
  'Cycle',
  'Liminal',
  'Binary',
  'Cube',
  'Magic',
  'Warmth',
  'Battery',
  'Music',
  'Grounded',
  'Cluttered',
  'Reload',
  'Story',
  'Animal',
  'Metal',
  'Rustic',
  'Simple',
  'Broken',
]

export const JAM_SUBMISSION_SCORE = 15

export const JAM_SCHEDULE = {
  timezone: 'America/New_York',
  generateCron: 'TZ=America/New_York 0 12 1 * *',
  reminderCron: 'TZ=America/New_York 0 12 15 * *',
  recapCron: 'TZ=America/New_York 0 9 1 * *',
  monthStartCron: 'TZ=America/New_York 0 0 1 * *',
  deadlineOffsetMs: 60_000,
} as const
